-- Where do the inpatient course records ("病程") live, and which table carries a
-- record-title column ("病案名称") that distinguishes 首次病程记录 / 入院记录?
-- Read-only discovery across the databases visible to this login.
SELECT 'SBO' AS db, TABLE_NAME, COLUMN_NAME FROM SBO.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE N'%病程%' OR TABLE_NAME LIKE N'%病案%'
   OR COLUMN_NAME LIKE N'%病案名称%' OR COLUMN_NAME LIKE N'%记录名称%'
UNION ALL
SELECT 'med_record', TABLE_NAME, COLUMN_NAME FROM med_record.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE N'%病程%' OR TABLE_NAME LIKE N'%病案%'
   OR COLUMN_NAME LIKE N'%病案名称%' OR COLUMN_NAME LIKE N'%记录名称%'
UNION ALL
SELECT 'records', TABLE_NAME, COLUMN_NAME FROM records.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE N'%病程%' OR TABLE_NAME LIKE N'%病案%'
   OR COLUMN_NAME LIKE N'%病案名称%' OR COLUMN_NAME LIKE N'%记录名称%'
UNION ALL
SELECT 'caiwu', TABLE_NAME, COLUMN_NAME FROM caiwu.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE N'%病程%' OR TABLE_NAME LIKE N'%病案%'
   OR COLUMN_NAME LIKE N'%病案名称%' OR COLUMN_NAME LIKE N'%记录名称%'
UNION ALL
SELECT 'his_qzzg', TABLE_NAME, COLUMN_NAME FROM his_qzzg.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE N'%病程%' OR TABLE_NAME LIKE N'%病案%'
   OR COLUMN_NAME LIKE N'%病案名称%' OR COLUMN_NAME LIKE N'%记录名称%'
UNION ALL
SELECT 'HospitalQC', TABLE_NAME, COLUMN_NAME FROM HospitalQC.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE N'%病程%' OR TABLE_NAME LIKE N'%病案%'
   OR COLUMN_NAME LIKE N'%病案名称%' OR COLUMN_NAME LIKE N'%记录名称%'
ORDER BY db, TABLE_NAME;
